# Generated by Django 3.2.13 on 2022-07-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_instrument_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument_Manager',
        ),
    ]
