# Generated by Django 4.0.4 on 2022-05-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('instrument_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('instrument_description', models.TextField(blank=True, max_length=500)),
                ('instrument_quantity', models.IntegerField()),
                ('instrument_image', models.ImageField(blank=True, upload_to='photos/instrument')),
                ('link', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
        ),
    ]
