# Generated by Django 3.2.13 on 2022-07-02 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_remove_instrument_instrument_id_instrument_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.instrument')),
            ],
        ),
    ]
