# Generated by Django 3.2.13 on 2022-07-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0003_instrument_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument_Manager',
        ),
    ]
