# Generated by Django 4.0.4 on 2022-05-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('institute_address', models.TextField(blank=True, max_length=511)),
                ('institute_contact', models.IntegerField()),
                ('institute_email', models.EmailField(max_length=100, unique=True)),
                ('pincode', models.IntegerField()),
                ('institute_image', models.ImageField(blank=True, upload_to='photos/institute')),
            ],
        ),
    ]
